name: build ebook

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SHA: ${{ github.sha }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libopengl0 libxcb-cursor-dev

      - name: Install Calibre
        run: sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sudo sh /dev/stdin

      - name: Install GitBook CLI
        run: sudo npm install -g gitbook-cli

      - name: Install GitBook plugins
        run: gitbook install

      - name: Build eBooks
        run: |
          mkdir -p output
          gitbook pdf . output/typescript-book-${SHA}.pdf
          gitbook epub . output/typescript-book-${SHA}.epub
          gitbook mobi . output/typescript-book-${SHA}.mobi

      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: typescript-book.pdf
          path: output/typescript-book-${{ env.SHA }}.pdf

      - name: Upload EPUB artifact
        uses: actions/upload-artifact@v4
        with:
          name: typescript-book.epub
          path: output/typescript-book-${{ env.SHA }}.epub

      - name: Upload MOBI artifact
        uses: actions/upload-artifact@v4
        with:
          name: typescript-book.mobi
          path: output/typescript-book-${{ env.SHA }}.mobi
